site_name: "Spreadsheet Basic Guide"
nav:
  - Intro:
    - spreadsheet_intro.md
  - Basics: 
    - spreadsheet_t1.md
    - spreadsheet_t2.md
    - spreadsheet_t3.md
  - Functions:
    - spreadsheet_t4_function.md
    - spreadsheet_t4_cell.md
    - 'Task 4.1 - SUM Function' : spreadsheet_t4_1.md
    - 'Task 4.2 - AVERAGE Function': spreadsheet_t4_2.md
    - 'Task 4.3 - MAX and MIN' : spreadsheet_t4_3.md
    - 'Task 4.4 - COUNTIF' : spreadsheet_t4_4.md
    - 'Task 4.5 - IF' : spreadsheet_t4_5.md

  - Extra:
    - spreadsheet_t5.md
  # - 'Word Processor':
  #   - word_L1.md
  # - 'Presentation':
  #   - presentation_L1.md


theme: 
  name: readthedocs
  collapse_navigation: True

plugins:
  - mkdocs-video

markdown_extensions:
  - attr_list